### ISSUE TITLE
Usage of ODOO_ADMIN_PASSWD

### ISSUE THREAD

**Issue by pniederlag** [initOS/dob#8]
Hi,

running [.setup.sh](setup.sh]) i get a .env with a Random PW for ODOO_ADMIN_PASSWD. 

However, it seems this is currently unused in the default project configuration. This probably makes it hard for first time users of this nice generic project template.

So either droping this Variable from .env or clearifying the intended usage would probably be helpful.

thx and cheers,
Peter

**Comment by azoellner** [comment]
The `ODOO_ADMIN_PASSWD` in the .env is assigned to the entry `options.admin_passwd` in the odoo/etc/odoo.cfg. This is used as a [password for database management from the web interface](https://www.odoo.com/documentation/master/administration/on_premise/deploy.html?highlight=admin_passwd#database-manager-security), which is is intended for development purposes only, and is not recommended for use in production systems. See the link for more details.
